### ISSUE TITLE
Backpressure

### ISSUE THREAD

**Issue by rassmate** [FroMage/reactivecontexts#1]
I am trying your library out and i works most of the time but I am having problems with backpressure.

I created a little test to reproduce my problem.
https://github.com/rassmate/reactive-contexts/blob/bugfix/handle_backpressure/tests/src/test/java/io/reactiverse/reactivecontexts/test/BackPressureExceptionTest.java

I am using rxjava 1 and have no possibility to switch unfortunately.

Thankful for any insights to help me around this problem.
@FroMage

**Comment by FroMage** [comment]
Fixed by #2 Thanks!

**Comment by FroMage** [comment]
Version 1.0.1 is released in Maven Central. But be aware this may be the last version released, as this project was rewritten as part of Microprofile Context Propagation: https://github.com/eclipse/microprofile-context-propagation
